### ISSUE TITLE
Manufacturer Posts (manufacturer-post)

### ISSUE THREAD

**Issue by FailureMaster** [FailureMaster/sel-frontend#21]
Please adjust from 768px to 1199px and make the amount go to the right side: 

![image](https://github.com/user-attachments/assets/f50a8983-3c68-45c6-88f8-d4d140c62aea)

@limplaton

**Comment by limplaton** [comment]
![image](https://github.com/user-attachments/assets/232433e6-fe61-4c6a-ba10-54a7d9fbd81e)

**Comment by FailureMaster** [comment]
Also do this in Apparel post. @limplaton , Let me know when it is done.
