### ISSUE TITLE
Manufacturer Quotations (manufacturer-quotations)

### ISSUE THREAD

**Issue by FailureMaster** [FailureMaster/sel-frontend#22]
**Adjust**:  768px to 887px — Make it two columns like this: 

Basically layout should be similar how 576px looks like:
![image](https://github.com/user-attachments/assets/df945dd2-ca2a-4c48-a8b1-547bb53ec92d)

@limplaton

**Comment by FailureMaster** [comment]
Adjust this the amount to the right on this screen range:  **380px** to **575px** Screen: 

Please do justify-between
![image](https://github.com/user-attachments/assets/da233a91-529e-4a09-8ff3-9e13d1cdd357)

**Comment by limplaton** [comment]
![image](https://github.com/user-attachments/assets/0e702f69-6c02-40a5-a8a6-90dbd0149452)

![image](https://github.com/user-attachments/assets/1a3c3e72-b5db-4e0b-97da-5e45c8b4174b)

**Comment by FailureMaster** [comment]
@limplaton , try making justify-content: space-around
