### ISSUE TITLE
Manufacturer Post Open (manufacturer-post-open)

### ISSUE THREAD

**Issue by FailureMaster** [FailureMaster/sel-frontend#23]
Please add a separator, just very light gray so if it goes to mobile, the user will know which one is:

![image](https://github.com/user-attachments/assets/c0995c5c-4769-40c8-bc9b-501a6295da99)

**Comment by FailureMaster** [comment]
Make the button in 406px and below to be full width:

![image](https://github.com/user-attachments/assets/04bd66f3-c59f-400a-b6a2-0ea90627edd7)

**Comment by limplaton** [comment]
![image](https://github.com/user-attachments/assets/bd87e668-9328-40d9-b1ef-ab2a41c9bd4e)

![image](https://github.com/user-attachments/assets/1e5305eb-322b-4bf6-b79e-894835e64820)
