### ISSUE TITLE
Apparel Quotations Page (apparel-quotations)

### ISSUE THREAD

**Issue by FailureMaster** [FailureMaster/sel-frontend#31]
Please make the Apparel text to be the same in the XD file. It should be Manufacturer because you are in apparels dashboard. 

**Wrong:**
![image](https://github.com/user-attachments/assets/cfaa8567-f3a8-49a6-932a-6314814d33f1)

**Right**
![image](https://github.com/user-attachments/assets/d82981a0-c044-4b2a-8c85-bf3350fbb809)

**Comment by FailureMaster** [comment]
Make sure the Button is **Order**, not _show_
![image](https://github.com/user-attachments/assets/3c66096f-8971-45b6-ab2f-2d3fe92603fd)

**Comment by limplaton** [comment]
![image](https://github.com/user-attachments/assets/25e91e49-a290-40d4-8f12-734f5ee169ac)
